name: build and deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.100
          
      - name: dotnet tool restore
        run: "dotnet tool restore"

      - name: install nodejs dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
        
      - name: build
        run: "./release.sh --base=/MySutilApp/"
        
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: dist
